Blog app - Views
ezekielgn/blog-app pull request #8
Opened 2023-08-24 22:31 UTC by PabloEGonz

In this branch, I worked on the following:

- Implement the design provided in the wireframes.
- Use the model's methods to display the data.
- Use Bootstrap to style the components.
- Create partials to use them in the views.

2023-08-24 23:30 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @PabloEGonz 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Use preprocessed HTML files with embedded Ruby code.
- ✔️ Use layouts and templates for shared content.


## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-24 23:30 UTC, abdulhamiid commented on app/views/posts/_post.html.erb
> +<div>
Your design
![image](https://github.com/PabloEGonz/blog-app/assets/78251927/b7c0ff97-c1ab-47dc-ac25-532fbc5e5515)

![image](https://github.com/PabloEGonz/blog-app/assets/78251927/396d974c-3605-4e64-b31d-bc623c65bf44)

According to the wireframe, please use the `post.recent_comments` to render the 5 most recent comments in the `app/views/posts/index.html.erb` page 🛠.

Only post show page displays the post with all comments listed as shown on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_single_post.png) 🤓

2023-08-24 23:30 UTC, abdulhamiid commented on app/views/posts/_post.html.erb
> +    <span>Likes <%= post.likes_counter%></span>
Error in the comments counter 
  - The counter displays `15` when there are `8` comments
![image](https://github.com/PabloEGonz/blog-app/assets/78251927/ad9c5199-1a46-4bb7-94d8-6c50e7c1cb4e)

I would suggest that you use `<%= post.comments.count %>` to fix the error in the comments counter

2023-08-24 23:30 UTC, abdulhamiid commented on app/views/shared/_user.html.erb
> +</div>
Good using rails views partials 👍

2023-08-25 01:00 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @PabloEGonz 👋, 

Great work on making the changes requested in the previous review 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️  Use preprocessed HTML files with embedded Ruby code.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 01:00 UTC, abdulhamiid commented on app/views/posts/_post.html.erb
> +    <span>Likes <%= post.likes_counter%></span>
As mentioned in the previous review, please fix the error in the comment counter so that it displays the correct number of comments in the database.

`http://127.0.0.1:3000/users/2/posts`
![image](https://github.com/PabloEGonz/blog-app/assets/78251927/634cca6c-8af2-4883-9e2f-e1fca574734e)

`Comment.all` (6 comments in the database) 👀
![image](https://github.com/PabloEGonz/blog-app/assets/78251927/ed4a0033-fc68-4b87-928f-dafe849dd583)

2023-08-25 01:00 UTC, abdulhamiid commented on app/views/posts/show.html.erb
> +      <small>Likes <%= @post.likes_counter%></small>
Also, on the Post show page, kindly fix the error in the counter so that the views function as expected. 🛠👍

`http://127.0.0.1:3000/users/2/posts/1`
![image](https://github.com/PabloEGonz/blog-app/assets/78251927/05fd6393-d310-4706-97bc-8e49124f1682)

2023-08-25 02:52 UTC, KanzaTahreem approved these changes
# Approved 🙌

Hi @PabloEGonz 

Good job implementing the suggested changes 💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media.tenor.com/xDHCe07zrocAAAAC/congrats-minions.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Error is fixed n the comment counter
-  ✅ Great work using the right GitFlow 
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 15:50 UTC, merged